const ACTION_TYPES = {
  SIGNUP_USERS: "SIGNUP_USERS",
  SIGNUP_USERS_SUCCESS: "SIGNUP_USERS_SUCCESS",
  SIGNUP_USERS_ERROR: "SIGNUP_USERS_ERROR",
  
  LOGIN_USERS: "LOGIN_USERS",
  LOGIN_USERS_SUCCESS: "LOGIN_USERS_SUCCESS",
  LOGIN_USERS_ERROR: "LOGIN_USERS_ERROR",

  ADD_BLOGS:"ADD_BLOGS",
  ADD_BLOGS_SUCCESS:"ADD_BLOGS_SUCCESS",
  ADD_BLOGS_ERROR:"ADD_BLOGS_ERROR",

  GET_BLOGS:"GET_BLOGS",
  GET_BLOGS_SUCCESS:"GET_BLOGS_SUCCESS",
  GET_BLOGS_ERROR:"GET_BLOGS_ERROR",

  UPDATE_BLOGS:"UPDATE_BLOGS",
  UPDATE_BLOGS_SUCCESS:"UPDATE_BLOGS_SUCCESS",
  UPDATE_BLOGS_ERROR:"UPDATE_BLOGS_ERROR",

  DELETE_BLOGS:"DELETE_BLOGS",
  DELETE_BLOGS_SUCCESS:"DELETE_BLOGS_SUCCESS",
  DELETE_BLOGS_ERROR:"DELETE_BLOGS_ERROR",

  IS_OPEN:"IS_OPEN",
};

export { ACTION_TYPES };
